
spring:
  data:
    mongodb:
      uri: mongodb+srv://rahul2148kumar:iawyybB4QXIIUTD5@cluster0.vvonv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index: true

server:
  port: 8081
  servlet:
    context-path: /journal